### ISSUE TITLE
My settings for compiling OCTproZ

### ISSUE THREAD

**Issue by Ledinor** [spectralcode/OCTproZ#12]
### These settings worked for me to compile octproz_project.pro
QT Version: Desktop Qt 5.12.10 MSVC2017 64bit
Compiler C/C++: Compiler 14.0 (x86_amd64)
CUDA: cuda_9.0.176_win10

1. Use jom.exe instead of cmake! Even when I checked “Use jom instead of nmake” (settings > Build & Run), Qt Ctreator did not use it. Therefore, I use it manually. So UNCHECK this jom setting.
-	Download jom 1.1.0
-	In Build settings, Build steps > details, instead C:\yourpath\nmake.exe use: select the directory of the jom.exe
-	No arguments for make (delete “clear” if this is pre-set)
-	Uncheck “disable in subdirectories” 
-	Do the same for the “Clean Steps”

2. Qt also seems to miss the location of the rc.exe (I do not know what it does). I add the rc.exe path in “Build Environment” under PATH (for me C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64)

3. After building the release file I had to add multiple QT.dll from the Qt bin folder to the release folder where the OCTproZ.exe is. For me: QT5Gui.dll, QT5Widgets.dll, QT5Core.dll, QT5PrintSupport.dll

4. I had a compile error that virtualoctsystemsettingsdialog.ui could not be found, anyway it was in the correct folder. The problem solves itself when I put everything on the same hard drive as the QT installation folder. (C:/ for me)

**Comment by spectralcode** [comment]
Hi @Ledinor, thank you very much for sharing your Qt Creator configuration! I created a troubleshooting section in [BUILD.md](https://github.com/spectralcode/OCTproZ/blob/master/BUILD.md) and copied your text there as it can help others who are facing similar issues.
Do you still have the inital error message? It may help others to see if they have the same problem.

**Comment by spectralcode** [comment]
I think I ran into a similar problem that you had.
After installing Qt (Qt 5.12.11 offline installer), Cuda and MSVC on a new machine I was not able to compile OCTproZ with the Qt Creator version provided with the Qt installer. 

The error message I received was:
`NMAKE : fatal error U1077: "C:\Program": Rückgabe-Code "0x1""`

To solve this issue I installed Qt Cretor 4.14.2 with the offline installer form here: 
https://download.qt.io/official_releases/qtcreator/4.14/4.14.2/ 

Then I deleted toolchains.xml. You can find the file here:
`C:\Users\%USERNAME%\AppData\Roaming\QtProject\qtcreator\toolchains.xml`

After these steps everything worked fine.
