### ISSUE TITLE
CUDA Kernel Order Question

### ISSUE THREAD

**Issue by chenw11** [spectralcode/OCTproZ#14]
I'm looking at the kernel execution order at the CUDA timeline, and it seems to me that data processing kernels started with the async memcpy kernel (inputCast), and ended before the images async copy is done (meanAlineSubtraction). Am I missing anything? If so, how do you ensure memcpy is not in race condition with these data processing kernels? Thanks in advanced for your answer.

**Comment by spectralcode** [comment]
Hi, this is a great observation and I think you may have found a possible race condition. Thank you!

To avoid race conditions, two measures were taken:
- in the cuda processing pipeline cudaStreamSynchronize for the memcpy stream is used
- in processing.cpp a flag that indicates if a buffer can be reused by the acquisition system (_bufferReadyArray_ ) is set to false after the cuda processing pipeline is started. This flag is set back to true in the acquisition system as soon as new data is available.  

Now looking at that part of the code again I think that _bufferReadyArray_ maybe should be set to false inside the cuda kernel right after async memcpy is done (_cudaStreamWaitEvent_ could be used to find out when async memcpy is done) or the cuda flag [cudaDeviceScheduleBlockingSync ](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__STREAM.html#group__CUDART__STREAM_1g82b5784f674c17c6df64affe618bf45e) should be used to block the host thread until the memcpy stream is finished 

Still, it may be possible that the acquisition is much faster than the processing and cudaMemcpyAsync is copying data to a buffer that has not yet been processed (but should have been) or is being processed at the same time. That's exactly the race condition you mean, right?

Again, thank you very much. This needs further investigation and should be handled somehow.

**Comment by chenw11** [comment]
I think my concern on the race condition is more about the execution location of these data processing kernels in the timeline. Because from what I see, the data is being async copy to the GPU, while the processing is taking place at the same time. This is where I'm worry would cause race condition, because how do you ensure all the data (for instance a B-Scan) is finished copied and thus your data processing kernels could access all the data that it suppose to. In another word, from what I see, there is a churn of data still being async copy to the GPU, but the meanAlineSubstraction is already stated. I think the stream orders are racing with each other.

During my testing, I found synchronizing the memcpy stream then the kernel stream after calling all data processing kernels seems resolve this problem. In this case. no data processing will be happened until async copy is finished, the CUDA timeline looks something like the following:
![Cuda Timeline](https://user-images.githubusercontent.com/17182101/106664297-dd651b00-6572-11eb-90cc-4d1c8402e76c.JPG)

On the other hand, for the race condition between the acquisition and the processing speed. I would consider that as a normal condition. It is just the matter of the user preference, if one want to see the latest image or the sequential images instead. And this should be able to address using the Image acquisition card API to store the latest or next frame in the buffer.

**Comment by spectralcode** [comment]
>  from what I see, the data is being async copy to the GPU, while the processing is taking place at the same time.

Yes, this is exactly how it is intended to be! New data is supposed to be copied while the previous data is being processed.
An optimal processing timeline looks somewhat like this:
![Visual Profiler - OCTproZ](https://raw.githubusercontent.com/spectralcode/OCTproZ/master/images/visualprofilerLabPC.png)
This image is from [performance.md](https://github.com/spectralcode/OCTproZ/blob/master/performance.md)

A double buffer approach is used: there are two buffers for oct data that get swept back and forth to avoid memcpy and processing kernels accessing the same buffer at the same time. One buffer is used for processing while the other one is used for memcpy. When one buffer is done with being processed this processing-buffer will be the new memcpy-buffer and the previous memcpy-buffer will be the new processing-buffer.
