### ISSUE TITLE
[Bug Report] Missing Nvidia Touring & Ampere Support

### ISSUE THREAD

**Issue by timm-landes** [spectralcode/OCTproZ#16]
**Describe the bug**
Code won't build due to missing support of:

- Turing – GTX 1660 Ti, RTX 2060, RTX 2070, RTX 2080, Titan RTX, Quadro RTX 4000, Quadro RTX 5000, Quadro RTX 6000, Quadro RTX 8000, Quadro T1000/T2000, Tesla T4 
- Ampere – Tesla GA10x cards, RTX Ampere – RTX 3080, GA102 – RTX 3090, RTX A6000, NVIDIA A40, GA106 – RTX 3060, GA104 – RTX 3070, GA107 – RTX 3050

**To Fix**
When using a Touring or Ampere card change in cuda.pri:
`
CUDA_ARCH += sm_30 \
-gencode=arch=compute_30,code=sm_30 \
-gencode=arch=compute_50,code=sm_50 \
-gencode=arch=compute_52,code=sm_52 \
-gencode=arch=compute_60,code=sm_60 \
-gencode=arch=compute_61,code=sm_61 \
-gencode=arch=compute_70,code=sm_70 \
`
to
`
CUDA_ARCH += sm_52 \ 
-gencode=arch=compute_52,code=sm_52 \ 
-gencode=arch=compute_60,code=sm_60 \ 
-gencode=arch=compute_61,code=sm_61 \ 
-gencode=arch=compute_70,code=sm_70 \ 
-gencode=arch=compute_75,code=sm_75 \
-gencode=arch=compute_80,code=sm_80 \
-gencode=arch=compute_86,code=sm_86 \
-gencode=arch=compute_86,code=compute_86
`
for max compatibility with newer architecture. Keep in mind that you may loose the compatibility for older generations & Jetson [Source](https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/).

**Used hardware**
 - OS: popOS
 - GPU: Nvidia GTX 1660 Super

**Comment by spectralcode** [comment]
Thanks. I've added a comment in [cuda.pri](https://github.com/spectralcode/OCTproZ/blob/master/octproz_project/octproz/pri/cuda.pri) regarding the gpu architecture flags.
The compilation instructions in [BUILD.md](https://github.com/spectralcode/OCTproZ/blob/master/BUILD.md) now also contain this information.
