### ISSUE TITLE
System crash w/o error message

### ISSUE THREAD

**Issue by BOle-ProZ** [spectralcode/OCTproZ#18]
**Describe the bug**
The program closes after the acquisiton is started. This does not happen when I delete the "emit this->system->acquisitionStarted(this->system);" line from my OCT system acquisition thread.

**Expected behavior**
Not crash

**Screenshots**
Because there is no error message, I cannot provide a screenshot.

**Used hardware**
 - OS: Win 10 64bit
 - GPU: Nvidia GTX 670

**Additional context**
Did anyone encounter a similar issue?

**Comment by spectralcode** [comment]
The issue is maybe related to the buffer size or to the implementation of your OCT system. 
Does this also happen if you decrease the buffer size?
How do you create the acquisition buffer? Could you post your code?

**Comment by BOle-ProZ** [comment]
The application crashes for every buffer size I set. The virtual OCT system also crashes, So it is a probably a hardware issue (CUDA something)

**Comment by BOle-ProZ** [comment]
Update: My GPU (wrongfully identified as 670 is actually a GTX 590) was too old for the CUDA flags I set. Using CUDA 8.0 and removing flags abough 52 and setting the lowest to 20 worked. Also, I had to reduce the Buffersize when using the VirtualOCTSystem to be able to see anything because my GPU is too weak.

**Comment by spectralcode** [comment]
Great, thanks for the update!
