### ISSUE TITLE
Is the project still being maintained? CUDA 12 has disabled some functions.

### ISSUE THREAD

**Issue by yankun2024** [spectralcode/OCTproZ#25]
https://github.com/spectralcode/OCTproZ/blob/094df9e2f00a47ab40f579a0004840acffebf260/octproz_project/octproz/src/cuda_code.cu#L43

, But, thank you! author. This is the most valuable project I've found on GitHub recently.

**Comment by spectralcode** [comment]
Hi yankun2024, yes, the project is still actively maintained. You are correct that some CUDA features, such as Surface Reference Management, have been deprecated and are not supported in the most recent CUDA version. I plan to address these issues in a future update (however, there is no timeline).

If you already have ideas for updating the deprecated functions while maintaining compatibility with older CUDA versions, please feel free to submit a pull request.

If you need a quick fix and want to use OCTproZ with the current CUDA version, you can comment out all the deprecated code. This will disable volume rendering, but everything else should still function properly.
