### ISSUE TITLE
Unable to View Test Dataset

### ISSUE THREAD

**Issue by RC-2000** [spectralcode/OCTproZ#7]
**Describe the bug**
For some reason I am unable to view the sample dataset. I am getting an entirely black screen, frequently with a message like this: 16:15:32 ERROR: No system opened!.

**To Reproduce**
Followed all steps in the user guide. Settings exactly as given in the images and descriptions at: https://figshare.com/articles/SSOCT_test_dataset_for_OCTproZ/12356705

**Expected behavior**
Expected to see the image included in the aforementioned link.

**Screenshots**
Expected:
![image](https://user-images.githubusercontent.com/25066876/97819245-55baf800-1c75-11eb-9c03-ca65a72bbea2.png)

My Output:
![image](https://user-images.githubusercontent.com/25066876/97818870-125f8a00-1c73-11eb-8b51-e2fa719940a2.png)

**Used hardware**
 - OS: Win 10 64bit
- GPU: Intel(R) UHD Graphics 620

**Comment by spectralcode** [comment]
Based on the error message from your screenshot ("No system opened!") I suspect that the Virtual OCT System is not opened. 
Click on File → Open System and click on Virtual OCT System then click on "Select" and try again. You can find more details in the user manual.

If it still doesn't work, your system may not have an Nvidia graphics card. OCTproZ requires a cuda-compatible graphics card with current drivers.

**Comment by RC-2000** [comment]
Yes, the Virtual OCT opens after several attempts. The error message appeared quite frequently, but I was able to get the Virtual OCT System in the image shown above. However, all the images in the dataset show up as totally black. My graphics card is Intel(R) UHD Graphics 620. So I suppose this wouldn't be compatible?

**Comment by spectralcode** [comment]
Right, it doesn't work with Intel GPUs.
